replicaCount: 1

image:
  repository: ghcr.io/goshlanguage/stock-exporter
  pullPolicy: IfNotPresent
  tag: "latest"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
