apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stock-exporter-monitor
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - port: "9090"
    path: /metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: stock-exporter
