apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9090"
  name: stock-exporter
spec:
  ports:
  - port: 9090
    protocol: TCP
  selector:
    app: stock-exporter
