name: Package and Publish Helm Chart

on: [push]

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: goshlanguage
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/goshlanguage/stock-exporter:latest
            ghcr.io/goshlanguage/lab:${{ github.sha }}
          platforms: linux/amd64,linux/arm64,linux/riscv64
